# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bazzite-base-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: "bazzite-base"
          containerfiles: "bazzite-base/Containerfile"
          image: bazzite-base
          layers: false
          oci: true

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: bazzite-base
          tags: "latest"
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
